name: hello-snap-q4n8x
base: core24
version: '0.1'
summary: A simple hello world snap
description: |
  Prints "Hello, World!" to the terminal.

grade: stable
confinement: strict

apps:
  hello-snap-q4n8x:
    command: bin/hello

parts:
  hello-snap-q4n8x:
    plugin: dump
    source: .
    organize:
      hello: bin/hello
